import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
          <meta charSet="UTF-8"/>
          <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
          <meta name="google-site-verification" content="0ohwv8fp9y2lDbJvO3wlop_RGWLT_B1HFT4WB64T5vk" />
          <title>Nicholas Tranquilli</title>
      
          <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" />
      
          <link href="main.css" rel="stylesheet" />
          <link href="main.js" rel="stylesheet" />
      </head>

      <body className={inter.className}>{children}</body>
    </html>
  );
}
